CREATE TABLE IF NOT EXISTS llm_configs (
    id TEXT PRIMARY KEY,
    config_data TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
